/* This file was generated by syncqt. */
#ifndef QT_QTWEBVIEW_VERSION_H
#define QT_QTWEBVIEW_VERSION_H

#define QTWEBVIEW_VERSION_STR "6.2.4"

#define QTWEBVIEW_VERSION 0x060204

#endif // QT_QTWEBVIEW_VERSION_H
