/* This file was generated by syncqt. */
#ifndef QT_QTQMLDOM_VERSION_H
#define QT_QTQMLDOM_VERSION_H

#define QTQMLDOM_VERSION_STR "6.2.4"

#define QTQMLDOM_VERSION 0x060204

#endif // QT_QTQMLDOM_VERSION_H
