SYNCQT.HEADER_FILES = 
SYNCQT.GENERATED_HEADER_FILES = qtaxbaseversion.h QtAxBaseVersion QtAxBase 
SYNCQT.PRIVATE_HEADER_FILES = qaxtypefunctions_p.h qaxutils_p.h 
SYNCQT.QPA_HEADER_FILES = 
SYNCQT.CLEAN_HEADER_FILES = 
SYNCQT.INJECTIONS = 
