/* This file was generated by syncqt. */
#ifndef QT_QTAXBASE_VERSION_H
#define QT_QTAXBASE_VERSION_H

#define QTAXBASE_VERSION_STR "6.2.4"

#define QTAXBASE_VERSION 0x060204

#endif // QT_QTAXBASE_VERSION_H
