SYNCQT.HEADER_FILES = qscxmlcompiler.h qscxmlcppdatamodel.h qscxmldatamodel.h qscxmlerror.h qscxmlevent.h qscxmlexecutablecontent.h qscxmlglobals.h qscxmlinvokableservice.h qscxmlnulldatamodel.h qscxmlstatemachine.h qscxmltabledata.h 
SYNCQT.GENERATED_HEADER_FILES = QScxmlCompiler QScxmlCppDataModel QScxmlDataModel QScxmlError QScxmlEvent QScxmlInvokableService QScxmlInvokableServiceFactory QScxmlStaticScxmlServiceFactory QScxmlDynamicScxmlServiceFactory QScxmlNullDataModel QScxmlStateMachine QScxmlTableData qtscxmlversion.h QtScxmlVersion QtScxml 
SYNCQT.PRIVATE_HEADER_FILES = qscxmlcompiler_p.h qscxmlcppdatamodel_p.h qscxmldatamodel_p.h qscxmldatamodelplugin_p.h qscxmlevent_p.h qscxmlexecutablecontent_p.h qscxmlglobals_p.h qscxmlinvokableservice_p.h qscxmlstatemachine_p.h qscxmlstatemachineinfo_p.h qscxmltabledata_p.h 
SYNCQT.QPA_HEADER_FILES = 
SYNCQT.CLEAN_HEADER_FILES = qscxmlcompiler.h qscxmlcppdatamodel.h qscxmldatamodel.h qscxmlerror.h qscxmlevent.h qscxmlexecutablecontent.h qscxmlglobals.h qscxmlinvokableservice.h qscxmlnulldatamodel.h qscxmlstatemachine.h qscxmltabledata.h 
SYNCQT.INJECTIONS = 
