SYNCQT.HEADER_FILES = 
SYNCQT.GENERATED_HEADER_FILES = qtqmlcoreversion.h QtQmlCoreVersion QtQmlCore 
SYNCQT.PRIVATE_HEADER_FILES = qqmlcoreglobal_p.h qqmlstandardpaths_p.h 
SYNCQT.QPA_HEADER_FILES = 
SYNCQT.CLEAN_HEADER_FILES = 
SYNCQT.INJECTIONS = 
