/* This file was generated by syncqt. */
#ifndef QT_QTQMLCORE_VERSION_H
#define QT_QTQMLCORE_VERSION_H

#define QTQMLCORE_VERSION_STR "6.2.4"

#define QTQMLCORE_VERSION 0x060204

#endif // QT_QTQMLCORE_VERSION_H
