SYNCQT.HEADER_FILES = 
SYNCQT.GENERATED_HEADER_FILES = qttoolsversion.h QtToolsVersion QtTools 
SYNCQT.PRIVATE_HEADER_FILES = 
SYNCQT.QPA_HEADER_FILES = 
SYNCQT.CLEAN_HEADER_FILES = 
SYNCQT.INJECTIONS = 
