/* This file was generated by syncqt. */
#ifndef QT_QTUIPLUGIN_VERSION_H
#define QT_QTUIPLUGIN_VERSION_H

#define QTUIPLUGIN_VERSION_STR "6.2.4"

#define QTUIPLUGIN_VERSION 0x060204

#endif // QT_QTUIPLUGIN_VERSION_H
