SYNCQT.HEADER_FILES = qtquick3dparticlesglobal.h 
SYNCQT.GENERATED_HEADER_FILES = qtquick3dparticlesversion.h QtQuick3DParticlesVersion QtQuick3DParticles 
SYNCQT.PRIVATE_HEADER_FILES = qquick3dparticle_p.h qquick3dparticleabstractshape_p.h qquick3dparticleaffector_p.h qquick3dparticleattractor_p.h qquick3dparticledata_p.h qquick3dparticledirection_p.h qquick3dparticleemitburst_p.h qquick3dparticleemitter_p.h qquick3dparticlegravity_p.h qquick3dparticlemodelblendparticle_p.h qquick3dparticlemodelparticle_p.h qquick3dparticlemodelshape_p.h qquick3dparticlepointrotator_p.h qquick3dparticlerandomizer_p.h qquick3dparticleshape_p.h qquick3dparticlespriteparticle_p.h qquick3dparticlespritesequence_p.h qquick3dparticlesystem_p.h qquick3dparticlesystemlogging_p.h qquick3dparticletargetdirection_p.h qquick3dparticletrailemitter_p.h qquick3dparticleutils_p.h qquick3dparticlevectordirection_p.h qquick3dparticlewander_p.h qtquick3dparticlesglobal_p.h 
SYNCQT.QPA_HEADER_FILES = 
SYNCQT.CLEAN_HEADER_FILES = qtquick3dparticlesglobal.h 
SYNCQT.INJECTIONS = 
