/* This file was generated by syncqt. */
#ifndef QT_QTSENSORS_VERSION_H
#define QT_QTSENSORS_VERSION_H

#define QTSENSORS_VERSION_STR "6.2.4"

#define QTSENSORS_VERSION 0x060204

#endif // QT_QTSENSORS_VERSION_H
