/* This file was generated by syncqt. */
#ifndef QT_QTQMLDEBUG_VERSION_H
#define QT_QTQMLDEBUG_VERSION_H

#define QTQMLDEBUG_VERSION_STR "6.2.4"

#define QTQMLDEBUG_VERSION 0x060204

#endif // QT_QTQMLDEBUG_VERSION_H
