/* This file was generated by syncqt. */
#ifndef QT_QTAXSERVER_VERSION_H
#define QT_QTAXSERVER_VERSION_H

#define QTAXSERVER_VERSION_STR "6.2.4"

#define QTAXSERVER_VERSION 0x060204

#endif // QT_QTAXSERVER_VERSION_H
