SYNCQT.HEADER_FILES = 
SYNCQT.GENERATED_HEADER_FILES = qtchartsqmlversion.h QtChartsQmlVersion QtChartsQml 
SYNCQT.PRIVATE_HEADER_FILES = declarativeabstractrendernode_p.h declarativeareaseries_p.h declarativeaxes_p.h declarativebarseries_p.h declarativeboxplotseries_p.h declarativecandlestickseries_p.h declarativecategoryaxis_p.h declarativechart_p.h declarativechartglobal_p.h declarativechartnode_p.h declarativeforeigntypes_p.h declarativelineseries_p.h declarativemargins_p.h declarativeopenglrendernode_p.h declarativepieseries_p.h declarativepolarchart_p.h declarativescatterseries_p.h declarativesplineseries_p.h declarativexypoint_p.h declarativexyseries_p.h 
SYNCQT.QPA_HEADER_FILES = 
SYNCQT.CLEAN_HEADER_FILES = 
SYNCQT.INJECTIONS = 
