SYNCQT.HEADER_FILES = 
SYNCQT.GENERATED_HEADER_FILES = qtmockstaticresources1version.h QtMockStaticResources1Version QtMockStaticResources1 
SYNCQT.PRIVATE_HEADER_FILES = 
SYNCQT.QPA_HEADER_FILES = 
SYNCQT.CLEAN_HEADER_FILES = 
SYNCQT.INJECTIONS = 
